# Generated by Django 6.0.5 on 2026-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_full_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
