# Generated by Django 6.0.5 on 2026-06-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login')], max_length=30),
        ),
    ]
