# Generated by Django 6.0.5 on 2026-07-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
