# Generated by Django 6.0.5 on 2026-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/audio/'),
        ),
    ]
