# Generated by Django 6.0.5 on 2026-06-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_remove_lecture_audio_file_alter_lecture_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_messages', to='lectures.lecture')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
