# Generated by Django 6.0.5 on 2026-07-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TimelineHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveIntegerField(help_text='Seconds from lecture start')),
                ('end_time', models.PositiveIntegerField(help_text='Seconds from lecture start')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('highlight_type', models.CharField(choices=[('concept', 'Concept'), ('equation', 'Equation')], default='concept', max_length=20)),
                ('equation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_highlights', to='lectures.lecture')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
